/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendataan_warga;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class daftar extends javax.swing.JFrame {

    private void kosong(){
        txtnik.setText("");
        txtkk.setText("");
        txtnama.setText("");
        cmbjk.setSelectedIndex(0);
        txttmpt.setText("");
        caltgl.setDate(null);
        cmbstatus.setSelectedIndex(0);
        txtalamat.setText("");
        txtnik.requestFocus();
        txtnotlp.setText("");
        cmbrumah.setSelectedIndex(0);
    }
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public daftar() {
        initComponents();
        kosong();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        txtkk = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        cmbjk = new javax.swing.JComboBox<>();
        cmbstatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        simpan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txttmpt = new javax.swing.JTextField();
        keluar = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        caltgl = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnotlp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbrumah = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NOMOR NIK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

        jLabel2.setText("NOMOR KK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        jLabel3.setText("NAMA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        jLabel4.setText("JENIS KELAMIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, -1));

        jLabel5.setText("TEMPAT/TANGGAL LAHIR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, -1, -1));

        jLabel6.setText("STATUS PERKAWINAN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, -1, -1));

        jLabel7.setText("ALAMAT");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, -1, -1));
        jPanel1.add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 68, 244, -1));
        jPanel1.add(txtkk, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 106, 244, -1));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 144, 244, -1));

        cmbjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Laki-Laki", "Perempuan" }));
        jPanel1.add(cmbjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 182, 130, -1));

        cmbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH==", "Belum Kawin", "Kawin", "Janda", "Duda" }));
        jPanel1.add(cmbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 259, 130, -1));

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 297, 244, -1));

        simpan.setText("Save");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 63, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("FORM DATA WARGA SIRNAGALIH");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));
        jPanel1.add(txttmpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 220, 110, -1));

        keluar.setText("Exit");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 64, -1));

        batal.setText("Cancel");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));
        jPanel1.add(caltgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 120, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 8)); // NOI18N
        jLabel12.setText("Created by Universitas Indraprasta");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));

        jLabel9.setText("NO.TELFON");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));
        jPanel1.add(txtnotlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 240, -1));

        jLabel10.setText("STATUS TINGGAL");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        cmbrumah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Rumah Sendiri", "Kontrakan" }));
        jPanel1.add(cmbrumah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO tb_data"
            +"(nik, kk, nama, jk, tmpt, tgl, status, alamat, no_tlp, rumah)"
            +"VALUES (?,?,?,?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sirnagalih","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1,txtnik.getText());
            pst.setString(2,txtkk.getText());
            pst.setString(3,txtnama.getText());
            pst.setString(4,cmbjk.getSelectedItem().toString());
            pst.setString(5,txttmpt.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format(caltgl.getDate());
            pst.setString(6,tanggal);
            pst.setString(7,cmbstatus.getSelectedItem().toString());
            pst.setString(8,txtalamat.getText());
            pst.setString(9,txtnotlp.getText());
            pst.setString(10,cmbrumah.getSelectedItem().toString());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
            kosong();
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        new menuawal_user().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private com.toedter.calendar.JDateChooser caltgl;
    private javax.swing.JComboBox<String> cmbjk;
    private javax.swing.JComboBox<String> cmbrumah;
    private javax.swing.JComboBox<String> cmbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton simpan;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtkk;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtnotlp;
    private javax.swing.JTextField txttmpt;
    // End of variables declaration//GEN-END:variables
}
