/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendataan_warga;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Admin
 */
public class data_warga_rt extends javax.swing.JFrame {

    
    private void kosong(){
        txtnik.setText("");
        txtkk.setText("");
        txtnama.setText("");
        cmbjk.setSelectedIndex(0);
        txttmpt.setText("");
        caltgl.setDate(null);
        cmbstatus.setSelectedIndex(0);
        txtalamat.setText("");
        txtnik.requestFocus();
        txtnotlp.setText("");
        cmbrumah.setSelectedIndex(0);
    }
    
    private void tampil_tabel(){
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("Nomor NIK");
        model.addColumn("Nomor KK");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tempat");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Status");
        model.addColumn("Alamat");
        model.addColumn("No Telfon");
        model.addColumn("Status Tinggal");
        try{
          int no = 1;
          String sql = "SELECT * FROM tb_data";
          java.sql.Connection conn =(Connection)koneksi.configDB();
          java.sql.Statement stm = conn.createStatement();
          java.sql.ResultSet res = stm.executeQuery(sql);
          
          while(res.next()){
              model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10)});
              }
          tabel_data.setModel(model);
        }catch (SQLException e){
            System.out.println("Error : "+ e.getMessage());
        }
            
    }
    /**
     * Creates new form data_warga_rt
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public data_warga_rt() {
        initComponents();
        tampil_tabel();
        kosong();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        txtkk = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        cmbjk = new javax.swing.JComboBox<>();
        cmbstatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txttmpt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        caltgl = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnotlp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbrumah = new javax.swing.JComboBox<>();
        jMenuBar2 = new javax.swing.JMenuBar();
        m_logout = new javax.swing.JMenu();
        m_menu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        m_data = new javax.swing.JMenuItem();
        m_iuaran = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        m_lap = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NOMOR NIK");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, -1, -1));

        jLabel2.setText("NOMOR KK");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        jLabel3.setText("NAMA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, -1, -1));

        jLabel4.setText("JENIS KELAMIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, -1));

        jLabel5.setText("TEMPAT/TANGGAL LAHIR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, -1, -1));

        jLabel6.setText("STATUS PERKAWINAN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, -1, -1));

        jLabel7.setText("ALAMAT");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, -1, -1));
        jPanel1.add(txtnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 68, 244, -1));
        jPanel1.add(txtkk, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 106, 244, -1));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 144, 244, -1));

        cmbjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Laki-Laki", "Perempuan" }));
        jPanel1.add(cmbjk, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 182, 130, -1));

        cmbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH==", "Belum Kawin", "Kawin", "Janda", "Duda" }));
        jPanel1.add(cmbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 259, 130, -1));

        txtalamat.setColumns(20);
        txtalamat.setRows(5);
        jScrollPane1.setViewportView(txtalamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 297, 244, -1));

        simpan.setText("Save");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 63, -1));

        ubah.setText("Edit");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        jPanel1.add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 63, -1));

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 170, -1));

        bcari.setText("Seacrh");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });
        jPanel1.add(bcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("FORM DATA WARGA SIRNAGALIH");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 21, -1, -1));
        jPanel1.add(txttmpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 220, 110, -1));

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        tabel_data.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabel_dataComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_data);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 40, -1, -1));

        hapus.setText("Delete");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        keluar.setText("Exit");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 64, -1));

        tambah.setText("Add");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 62, -1));

        batal.setText("Cancel");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));
        jPanel1.add(caltgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 120, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 8)); // NOI18N
        jLabel12.setText("Created by Universitas Indraprasta");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jLabel9.setText("NO.TELFON");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));
        jPanel1.add(txtnotlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 240, -1));

        jLabel10.setText("STATUS TINGGAL");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        cmbrumah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Rumah Sendiri", "Kontrakan" }));
        jPanel1.add(cmbrumah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 130, -1));

        jMenuBar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        m_logout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        m_logout.setText("Menu");
        m_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_logoutActionPerformed(evt);
            }
        });

        m_menu.setText("Menu Utama");
        m_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_menuActionPerformed(evt);
            }
        });
        m_logout.add(m_menu);

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        m_logout.add(jMenuItem2);

        jMenuBar2.add(m_logout);

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Master Data");

        m_data.setText("Data Warga");
        m_data.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_dataActionPerformed(evt);
            }
        });
        jMenu2.add(m_data);

        m_iuaran.setText("Iuaran Warga");
        m_iuaran.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m_iuaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_iuaranActionPerformed(evt);
            }
        });
        jMenu2.add(m_iuaran);

        jMenuBar2.add(jMenu2);

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("View");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        m_lap.setText("Laporan");
        m_lap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_lapActionPerformed(evt);
            }
        });
        jMenu1.add(m_lap);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_logoutActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_m_logoutActionPerformed

    private void m_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_dataActionPerformed
        // TODO add your handling code here:
        new data_warga_rt().setVisible(true);
        dispose();
    }//GEN-LAST:event_m_dataActionPerformed

    private void m_iuaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_iuaranActionPerformed
        // TODO add your handling code here:
        new iuaran_warga_rt().setVisible(true);
        dispose();
    }//GEN-LAST:event_m_iuaranActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        new laporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void m_lapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_lapActionPerformed
        // TODO add your handling code here:
        new laporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_m_lapActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        kosong();
        txtnik.requestFocus();
    }//GEN-LAST:event_tambahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO tb_data"
                    +"(nik, kk, nama, jk, tmpt, tgl, status, alamat, no_tlp, rumah)"
                    +"VALUES (?,?,?,?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sirnagalih","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1,txtnik.getText());
            pst.setString(2,txtkk.getText());
            pst.setString(3,txtnama.getText());
            pst.setString(4,cmbjk.getSelectedItem().toString());
            pst.setString(5,txttmpt.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format(caltgl.getDate());
            pst.setString(6,tanggal);
            pst.setString(7,cmbstatus.getSelectedItem().toString());
            pst.setString(8,txtalamat.getText());
            pst.setString(9,txtnotlp.getText());
            pst.setString(10,cmbrumah.getSelectedItem().toString());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
            tampil_tabel();
            kosong();
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void tabel_dataComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabel_dataComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel_dataComponentShown

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM tb_data WHERE nik='"+txtnik.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        tampil_tabel();
        kosong();
    }//GEN-LAST:event_hapusActionPerformed

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked
        // TODO add your handling code here:
        int baris = tabel_data.rowAtPoint(evt.getPoint());
        String nik = tabel_data.getValueAt(baris, 0).toString();
        txtnik.setText(nik);
        String kk = tabel_data.getValueAt(baris, 1).toString();
        txtkk.setText(kk);
        String nama = tabel_data.getValueAt(baris, 2).toString();
        txtnama.setText(nama);
        String jk = tabel_data.getValueAt(baris, 3).toString();
        cmbjk.setSelectedItem(jk);
        String tmpt = tabel_data.getValueAt(baris, 4).toString();
        txttmpt.setText(tmpt);
        try{
	DefaultTableModel model = (DefaultTableModel)tabel_data.getModel();
	int bar = tabel_data.getSelectedRow();
	Date tanggal = new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(bar, 5));
	caltgl.setDate(tanggal);
        }catch(ParseException ex){
	Logger.getLogger(data_warga_rt.class.getName()).log(Level.SEVERE, null, ex);
        }
        String status = tabel_data.getValueAt(baris, 6).toString();
        cmbstatus.setSelectedItem(status);
        String alamat = tabel_data.getValueAt(baris, 7).toString();
        txtalamat.setText(alamat);
        String no_tlp = tabel_data.getValueAt(baris, 8).toString();
        txtnotlp.setText(no_tlp);
        String rumah = tabel_data.getValueAt(baris, 9).toString();
        cmbrumah.setSelectedItem(rumah);
    }//GEN-LAST:event_tabel_dataMouseClicked

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String sql = "UPDATE tb_data SET nik='"+txtnik.getText()+"',kk='"+txtkk.getText()+"',nama='"+txtnama.getText()+"',jk='"+cmbjk.getSelectedItem()+"',tmpt='"+txttmpt.getText()+"',tgl='"+sdf.format(caltgl.getDate())+"',status='"+cmbstatus.getSelectedItem()+"',alamat='"+txtalamat.getText()+"',no_tlp='"+txtnotlp.getText()+"',rumah='"+cmbrumah.getSelectedItem()+"' WHERE nik='"+txtnik.getText()+"'";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sirnagalih","root","");
            pst = con.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            tampil_tabel();
            kosong();
            txtnik.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah" + e);
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Nomor NIK", "Nomor KK", "Nama", "Jenis Kelamin", "Tempat", "Tanggal Lahir", "Status", "Alamat", "No Telfon", "Status Tinggal"};
        DefaultTableModel tbl = new DefaultTableModel(null, Baris);
        tabel_data.setModel(tbl);
        String sql = "select * from tb_data where "+"nik like '%" + cari.getText() + "%' OR "+"nama like '%"+cari.getText()+"%'";
        try {
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            ResultSet hasil = pstm.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("nik");
                String b = hasil.getString("kk");
                String c = hasil.getString("nama");
                String d = hasil.getString("jk");
                String e = hasil.getString("tmpt");
                String f = hasil.getString("tgl");
                String g = hasil.getString("status");
                String h = hasil.getString("alamat");
                String i = hasil.getString("no_tlp");
                String j = hasil.getString("rumah");
                
                
                String[] data = {a, b, c, d, e, f, g, h, i, j};
                tbl.addRow(data);
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_bcariActionPerformed

    private void m_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_menuActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_m_menuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(data_warga_rt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(data_warga_rt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(data_warga_rt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(data_warga_rt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new data_warga_rt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton bcari;
    private com.toedter.calendar.JDateChooser caltgl;
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox<String> cmbjk;
    private javax.swing.JComboBox<String> cmbrumah;
    private javax.swing.JComboBox<String> cmbstatus;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keluar;
    private javax.swing.JMenuItem m_data;
    private javax.swing.JMenuItem m_iuaran;
    private javax.swing.JMenuItem m_lap;
    private javax.swing.JMenu m_logout;
    private javax.swing.JMenuItem m_menu;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel_data;
    private javax.swing.JButton tambah;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextField txtkk;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtnotlp;
    private javax.swing.JTextField txttmpt;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables

}
