/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pendataan_warga;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Admin
 */
public class iuaran_warga_rt extends javax.swing.JFrame {

        int bulanan;
        int kebersihan;
        int acara;
        int total;
        int iuran;
        int jumlah;
          
        private void kosong(){
        txtkd.setText("");
        txtnama.setText("");
        date.setDate(null);
        txtiuaran.setText("");
        txtkebersihan.setText("");
        txtbulan.setText("");
        txtacara.setText("");
        txttotal.setText("");
        }
    
        private void tampil_tabeliuaran(){
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("Kode Bayar");
        model.addColumn("Nama");
        model.addColumn("Tanggal Pembayaran");
        model.addColumn("Iuaran Bulanan");
        model.addColumn("Bulan Terbayar");
        model.addColumn("Iuaran Kebersihan");
        model.addColumn("Iuaran Acara");
        model.addColumn("Total Iuaran");
        try{
          int no = 1;
          String sql = "SELECT * FROM tb_iuaran_warga";
          java.sql.Connection conn =(Connection)koneksi.configDB();
          java.sql.Statement stm = conn.createStatement();
          java.sql.ResultSet res = stm.executeQuery(sql);
          
          while(res.next()){
              model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)});
              }
          tabel_iuaran.setModel(model);
        }catch (SQLException e){
            System.out.println("Error : "+ e.getMessage());
        }
            
    }
        //menjumlahkan isi colom ke 4 dalam tabel
    public final void auto_sum(){
    int txttotal = 0;
    for (int i =0; i< tabel_iuaran.getRowCount(); i++){
       int amount = Integer.parseInt((String)tabel_iuaran.getValueAt(i, 7));
       txttotal += amount;
}
    total_iuran.setText("RP. "+txttotal);
    }
    /**
     * Creates new form iuaran_warga_rt
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public iuaran_warga_rt() {
        initComponents();
        tampil_tabeliuaran();
        kosong();
        auto_sum();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtkd = new javax.swing.JTextField();
        txtbulan = new javax.swing.JTextField();
        txtkebersihan = new javax.swing.JTextField();
        txtacara = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtiuaran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_iuaran = new javax.swing.JTable();
        ubah = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        txtnama = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        total_iuran = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jMenuBar2 = new javax.swing.JMenuBar();
        m_home = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        m_data = new javax.swing.JMenuItem();
        m_iuaran = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        m_lap = new javax.swing.JMenuItem();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("FORM PEMBAYARAN IUARAN WARGA SIRNAGALIH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 360, -1));

        jLabel2.setText("KODE BAYAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 65, 120, -1));

        jLabel3.setText("NAMA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 100, -1, -1));

        jLabel4.setText("IURAN BULANAN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 181, -1, -1));

        jLabel5.setText("BULAN SUDAH DIBAYAR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 216, -1, -1));

        jLabel6.setText("IURAN KEBERSIHAN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 251, -1, -1));

        jLabel7.setText("IURAN ACARA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 289, -1, -1));
        jPanel1.add(txtkd, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 62, 201, -1));

        txtbulan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbulanMouseClicked(evt);
            }
        });
        jPanel1.add(txtbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 213, 130, -1));

        txtkebersihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkebersihanActionPerformed(evt);
            }
        });
        jPanel1.add(txtkebersihan, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 248, 201, -1));
        jPanel1.add(txtacara, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 286, 201, -1));

        jLabel8.setText("TANGGAL PEMBAYARAN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 143, -1, -1));
        jPanel1.add(txtiuaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 175, 201, -1));

        jLabel10.setText("TOTAL IURAN");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 327, -1, -1));

        txttotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttotalMouseClicked(evt);
            }
        });
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 324, 201, -1));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        tabel_iuaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_iuaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_iuaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_iuaran);

        ubah.setText("Edit");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        bcari.setText("Seacrh");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        tambah.setText("Add");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        simpan.setText("Save");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        hapus.setText("Delete");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        batal.setText("Cancel");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        keluar.setText("Exit");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(batal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bcari)
                .addGap(4, 20, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ubah)
                            .addComponent(tambah)
                            .addComponent(simpan)
                            .addComponent(hapus)
                            .addComponent(batal)
                            .addComponent(keluar)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bcari)
                        .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 260));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 103, 201, -1));

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Total Pemasukan Iuran");

        total_iuran.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        total_iuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total_iuranMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(total_iuran)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(total_iuran, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, 90));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 140, 200, -1));

        m_home.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        m_home.setText("Menu");
        m_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_homeActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Menu Utama");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        m_home.add(jMenuItem1);

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        m_home.add(jMenuItem2);

        jMenuBar2.add(m_home);

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("Master Data");

        m_data.setText("Data Warga");
        m_data.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_dataActionPerformed(evt);
            }
        });
        jMenu2.add(m_data);

        m_iuaran.setText("Iuaran Warga");
        m_iuaran.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        m_iuaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_iuaranActionPerformed(evt);
            }
        });
        jMenu2.add(m_iuaran);

        jMenuBar2.add(jMenu2);

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("View");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        m_lap.setText("Laporan");
        m_lap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_lapActionPerformed(evt);
            }
        });
        jMenu1.add(m_lap);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_batalActionPerformed

    private void m_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_homeActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_m_homeActionPerformed

    private void m_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_dataActionPerformed
        // TODO add your handling code here:
        new data_warga_rt().setVisible(true);
        dispose();
    }//GEN-LAST:event_m_dataActionPerformed

    private void m_iuaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_iuaranActionPerformed
        // TODO add your handling code here:
        new iuaran_warga_rt().setVisible(true);
        dispose();
    }//GEN-LAST:event_m_iuaranActionPerformed

    private void m_lapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_lapActionPerformed
        // TODO add your handling code here:
        new laporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_m_lapActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        new laporan().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_tambahActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "INSERT INTO tb_iuaran_warga"
                    +"(kd_byr, nama, date, iuaran, bulan, kebersihan, acara, total)"
                    +"VALUES (?,?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sirnagalih","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1,txtkd.getText());
            pst.setString(2,txtnama.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format(date.getDate());
            pst.setString(3,tanggal);
            pst.setString(4,txtiuaran.getText());
            pst.setString(5,txtbulan.getText());
            pst.setString(6,txtkebersihan.getText());
            pst.setString(7,txtacara.getText());
            pst.setString(8,txttotal.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Berhasil disimpan");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        tampil_tabeliuaran();
        kosong();
    }//GEN-LAST:event_simpanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "update tb_iuaran_warga set nama=?,date=?,iuaran=?,bulan=?,kebersihan=?,acara=?,total=? where kd_byr=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_sirnagalih","root","");
            pst = con.prepareStatement(sql);          
            
            pst.setString(1, txtnama.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tanggal = sdf.format(date.getDate());
            pst.setString(2, tanggal);
            pst.setString(3, txtiuaran.getText());
            pst.setString(4, txtbulan.getText());
            pst.setString(5, txtkebersihan.getText());
            pst.setString(6, txtacara.getText());
            pst.setString(7, txttotal.getText());
            pst.setString(8, txtkd.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            tampil_tabeliuaran();
            kosong();
            txtkd.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah" + e);
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void tabel_iuaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_iuaranMouseClicked
        // TODO add your handling code here:
        int baris = tabel_iuaran.rowAtPoint(evt.getPoint());
        String kd_byr = tabel_iuaran.getValueAt(baris, 1).toString();
        txtkd.setText(kd_byr);
        String nama = tabel_iuaran.getValueAt(baris, 2).toString();
        txtnama.setText(nama);
        try{
	DefaultTableModel model1 = (DefaultTableModel)tabel_iuaran.getModel();
	int bar = tabel_iuaran.getSelectedRow();
	Date tanggal = new SimpleDateFormat("yyyy-MM-dd").parse((String)model1.getValueAt(bar, 3));
	date.setDate(tanggal);
        }catch(ParseException ex){
	Logger.getLogger(iuaran_warga_rt.class.getName()).log(Level.SEVERE, null, ex);
        }
        String iuaran = tabel_iuaran.getValueAt(baris, 4).toString();
        txtiuaran.setText(iuaran);
        String bulan = tabel_iuaran.getValueAt(baris, 5).toString();
        txtbulan.setText(bulan);
        String kebersihan1 = tabel_iuaran.getValueAt(baris, 6).toString();
        txtkebersihan.setText(kebersihan1);
        String acara1 = tabel_iuaran.getValueAt(baris, 7).toString();
        txtacara.setText(acara1);
        String total1 = tabel_iuaran.getValueAt(baris, 8).toString();
        txttotal.setText(total1);
    }//GEN-LAST:event_tabel_iuaranMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "DELETE FROM tb_iuaran_warga WHERE kd_byr='"+txtkd.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        tampil_tabeliuaran();
        kosong();
    }//GEN-LAST:event_hapusActionPerformed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Kode Bayar", "Nama", "Tanggal Pembayaran", "Iuaran Bulanan", "Bulan Terbayar", "Iuran Kebersihan", "Iuran Acara", "Total Iuran"};
        DefaultTableModel tbl = new DefaultTableModel(null, Baris);
        tabel_iuaran.setModel(tbl);
        String sql = "select * from tb_iuran_warga where kd_byr like '%" + cari.getText() + "%' OR "+"nama like '%"+cari.getText()+"%'";
        try {
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            ResultSet hasil = pstm.executeQuery(sql);
            while (hasil.next()) {
                String a = hasil.getString("kd_byr");
                String b = hasil.getString("nama");
                String c = hasil.getString("date");
                String d = hasil.getString("iuran");
                String e = hasil.getString("bulan");
                String f = hasil.getString("kebersihan");
                String g = hasil.getString("acara");
                String h = hasil.getString("total");
                
                String[] data = {a, b, c, d, e, f, g, h};
                tbl.addRow(data);
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_bcariActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtkebersihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkebersihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkebersihanActionPerformed

    private void txttotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttotalMouseClicked
        // TODO add your handling code here:
        bulanan = Integer.parseInt(txtiuaran.getText());
        kebersihan = Integer.parseInt(txtkebersihan.getText());
        acara = Integer.parseInt(txtacara.getText());
        
        total = bulanan+kebersihan+acara;
        txttotal.setText(""+total);
    }//GEN-LAST:event_txttotalMouseClicked

    private void total_iuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total_iuranMouseClicked
        // TODO add your handling code here:
        auto_sum();
    }//GEN-LAST:event_total_iuranMouseClicked

    private void txtbulanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbulanMouseClicked
        // TODO add your handling code here:
        iuran = Integer.parseInt(txtiuaran.getText());
        
        jumlah = iuran/20000;
        
        txtbulan.setText(""+jumlah);
    }//GEN-LAST:event_txtbulanMouseClicked
    
    private void m_utamaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iuaran_warga_rt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iuaran_warga_rt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iuaran_warga_rt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iuaran_warga_rt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iuaran_warga_rt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton bcari;
    private javax.swing.JTextField cari;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton keluar;
    private javax.swing.JMenuItem m_data;
    private javax.swing.JMenu m_home;
    private javax.swing.JMenuItem m_iuaran;
    private javax.swing.JMenuItem m_lap;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabel_iuaran;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField total_iuran;
    private javax.swing.JTextField txtacara;
    private javax.swing.JTextField txtbulan;
    private javax.swing.JTextField txtiuaran;
    private javax.swing.JTextField txtkd;
    private javax.swing.JTextField txtkebersihan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttotal;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
